# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
api-spec.yaml:
  no-server-example.com:
    - '#/servers/0/url'
  no-server-trailing-slash:
    - '#/servers/1/url'
  operation-4xx-response:
    - '#/paths/~1version/get/responses'
  no-unused-components:
    - '#/components/schemas/AlleleList'
