FROM python:3.14-slim-trixie

LABEL MAINTAINER="Pradeep Bashyal"

WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY requirements-deploy.txt /app
RUN pip install --no-cache-dir -r requirements-deploy.txt

COPY pyard /app/pyard

COPY app.py /app/
COPY api.py /app/
COPY api-spec.yaml /app/
COPY gunicorn_config.py /app/

CMD ["gunicorn", "-c", "gunicorn_config.py", "--workers=4", "app:app"]
