#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    py-ard
#    Copyright (c) 2023 Be The Match operated by National Marrow Donor Program. All Rights Reserved.
#
#    This library is free software; you can redistribute it and/or modify it
#    under the terms of the GNU Lesser General Public License as published
#    by the Free Software Foundation; either version 3 of the License, or (at
#    your option) any later version.
#
#    This library is distributed in the hope that it will be useful, but WITHOUT
#    ANY WARRANTY; with out even the implied warranty of MERCHANTABILITY or
#    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
#    License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with this library;  if not, write to the Free Software Foundation,
#    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.
#
#    > http://www.fsf.org/licensing/licenses/lgpl.html
#    > http://www.opensource.org/licenses/lgpl-license.php
#
import argparse
import functools
import sys

from pyard import smart_sort
from pyard.constants import VALID_REDUCTION_TYPES
import pyard.misc
from pyard.db import similar_alleles, similar_mac
from pyard.exceptions import InvalidAlleleError, InvalidTypingError, InvalidMACError
from pyard.misc import get_data_dir, get_imgt_version


def find_similar_alleles(ard, prefix):
    if "*" in prefix:  # Only for those that have locus
        locus, fields = prefix.split("*")
        if fields:  # Only if at least a field is specified after *
            if len(fields.split(":")) == 2:  # Check for MACs
                first_field, mac_prefix = fields.split(":")
                if mac_prefix.isalpha():
                    similar_mac_names = similar_mac(ard.db_connection, mac_prefix)
                    if similar_mac_names:
                        locus_prefix = f"{locus}*{first_field}"
                        # TODO: validate all the mac codes with the prefix
                        #       show only the valid macs
                        for code in sorted(similar_mac_names):
                            print(f"{locus_prefix}:{code}")
        else:
            # Nothing after *
            sys.exit(2)
    else:
        # No *
        sys.exit(1)

    # find similar alleles
    similar_allele_names = similar_alleles(ard.db_connection, prefix)
    if similar_allele_names:
        for allele in sorted(
            similar_allele_names,
            key=functools.cmp_to_key(smart_sort.smart_sort_comparator),
        ):
            print(allele)
    sys.exit(0)


def lookup_mac_codes():
    global e
    try:
        mac = ard.lookup_mac(args.lookup_mac)
        print(mac)
    except InvalidMACError as e:
        print(e.message, file=sys.stderr)
    sys.exit(0)


def expand_mac_code():
    global allele_list, e
    try:
        allele_list = ard.expand_mac(args.expand_mac)
        print(allele_list)
    except InvalidMACError as e:
        print(e.message, file=sys.stderr)
    sys.exit(0)


def find_broad_splits():
    mapping = pyard.find_broad_splits(args.splits)
    if mapping:
        print(f"{mapping[0]} = {'/'.join(mapping[1])}")
    sys.exit(0)


def show_version():
    version = ard.get_db_version()
    print(f"IPD-IMGT/HLA version:", version)
    print(f"py-ard version:", pyard.__version__)
    sys.exit(0)


def perform_cwd_redux():
    global cwd_redux
    if args.validate:
        ard.validate(args.cwd)
    cwd_redux = ard.cwd_redux(args.cwd)
    print(cwd_redux)
    sys.exit(0)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="""
        py-ard tool to redux GL String
        """,
    )
    parser.add_argument(
        "-v",
        "--version",
        dest="version",
        action="store_true",
        help="IPD-IMGT/HLA DB Version number",
    )
    parser.add_argument(
        "-d",
        "--data-dir",
        dest="data_dir",
        help="Data directory to store imported data",
    )
    parser.add_argument(
        "-i",
        "--imgt-version",
        dest="imgt_version",
        help="IPD-IMGT/HLA db to use for redux",
    )
    parser.add_argument("-g", "--gl", dest="gl_string", help="GL String to reduce")
    parser.add_argument(
        "-r",
        "--redux-type",
        choices=VALID_REDUCTION_TYPES,
        dest="redux_type",
        help="Reduction Method",
    )
    parser.add_argument("--splits", dest="splits", help="Find Broad and Splits")
    parser.add_argument(
        "--validate",
        dest="validate",
        action="store_true",
        help="Validate the provided GL String",
    )
    parser.add_argument("--cwd", dest="cwd", help="Perform CWD redux")
    parser.add_argument(
        "--expand-mac", dest="expand_mac", help="Expand MAC to Allele List"
    )
    parser.add_argument(
        "--lookup-mac", dest="lookup_mac", help="Lookup MAC for an Allele List"
    )
    parser.add_argument(
        "--similar",
        dest="similar_allele",
        help="Find Similar Alleles with given prefix",
    )
    parser.add_argument(
        "--non-strict",
        dest="non_strict",
        action="store_true",
        help="Use non-strict mode",
    )
    parser.add_argument(
        "--verbose", dest="verbose", action="store_true", help="Use verbose mode"
    )

    args = parser.parse_args()

    imgt_version = get_imgt_version(args.imgt_version)
    data_dir = get_data_dir(args.data_dir)

    new_config = {}
    if args.non_strict:
        new_config["strict"] = False

    if args.verbose:
        new_config["verbose_log"] = True

    ard = pyard.init(imgt_version=imgt_version, data_dir=data_dir, config=new_config)

    # Handle --version option
    if args.version:
        show_version()

    # Handle --splits option
    if args.splits:
        find_broad_splits()

    # Handle --expand-mac option
    if args.expand_mac:
        expand_mac_code()

    # Handle --lookup-mac option
    if args.lookup_mac:
        lookup_mac_codes()

    # Handle --similar option
    if args.similar_allele:
        find_similar_alleles(ard, args.similar_allele)

    try:
        if args.cwd:
            perform_cwd_redux()

        if args.validate and args.gl_string:
            ard.validate(args.gl_string)

        if args.redux_type:
            print(ard.redux(args.gl_string, args.redux_type))
        else:
            for redux_type in VALID_REDUCTION_TYPES:
                redux_type_info = f"Reduction Method: {redux_type}"
                print(redux_type_info)
                print("-" * len(redux_type_info))
                print(ard.redux(args.gl_string, redux_type))
                print()
    except InvalidAlleleError as e:
        print("Allele Error:", e.message, file=sys.stderr)
        sys.exit(1)
    except InvalidTypingError as e:
        print("Typing Error:", e.message, file=sys.stderr)
        sys.exit(2)
    except InvalidMACError as e:
        print("MAC Error:", e.message, file=sys.stderr)
        sys.exit(3)
    else:
        # Remove ard and close db connection
        del ard
